---
title: "Probabilidades"
subtitle: "Capítulo 2"
description: "..."
author: "Prof. Dr. Raphael Teixeira"
date: "2026-08-02"
date-modified: last-modified
categories: [Probabilidade, Estatística, Chan, Python]
livro: "Chan — Introduction to Probability for Data Science"
autor-livro: "Stanley H. Chan"
capitulo: 2
status: rascunho
lang: pt-BR
---

## Probabilidades

- Dados: Perspectiva computacional;
- Probabilidade: Perspectiva matemática/teórica;
- Estatística: Perspectiva empírica;

- Frequencista: Probabilidade como frequência relativa de um evento em experimentos repetidos;
- Bayesiano: Probabilidade como grau de crença em um evento, dado o conhecimento disponível.

- A. Kolmogorov (1933): Probabilidade como medida de um espaço amostral.

### Probabilidade de um evento: Jogar um dado

- Seja um dado com 6 faces, numeradas de 1 a 6. O espaço amostral é:
$$\Omega = \{1, 2, 3, 4, 5, 6\}$$

- Qual a probabilidade de sair um número par? O evento é:
$$A = \{2, 4, 6\}$$

- A probabilidade de um evento é definida como:
$$P(A) = \frac{|A|}{|\Omega|}$$
$$P(A) = \dfrac{3}{6} = 0.5$$

Como sabemos que o denominador é 6? Porque o dado é justo, ou seja, todas as faces têm a mesma probabilidade de sair. Se o dado fosse viciado, teríamos que usar outro método para determinar a probabilidade.

