---
title: "Recomendações"
description: "Livros, sites e canais recomendados para aprofundamento em engenharia, ciência de dados e aprendizado de máquina, além de notas sobre o uso do Quarto."
---

Livros, sites e canais do YouTube recomendados para aprofundamento em temas relacionados a
engenharia, ciência de dados e aprendizado de máquina.

## Livros

[Introduction to Deep Learning](https://courses.d2l.ai/berkeley-stat-157/index.html)

## Sites

- [Pratical Machine Learning](https://c.d2l.ai/stanford-cs329p/index.html): Livro focado em aprendizado de máquina prático com implementações em Python.

- [Dicas de markdown para Quarto](https://quarto.org/docs/guide/): Guia oficial do Quarto destacando as diferenças e extensões do Markdown padrão.

- [PoSit](https://posit.co/): Plataforma que oferece ferramentas para ciência de dados, incluindo RStudio e suporte para Quarto.

- [IntroDeepLearningMIT](https://introtodeeplearning.com/): Curso introdutório ao aprendizado profundo oferecido pelo MIT, com foco em aplicações práticas.

## Canais YouTube

[3Blue1Brown](https://www.youtube.com/@3blue1brown): Canal focado em matemática visual, cobrindo tópicos como álgebra linear, cálculo e aprendizado de máquina.

## Quarto

O que vou aprendendo com Quarto e Markdown para desenvolvimento deste site e de outros documentos de ensino e pesquisa.

**Quarto** é uma ferramenta de código aberto para criação de documentos dinâmicos, sites, blogs e apresentações. Ele suporta múltiplos formatos de saída, incluindo HTML, PDF e Word, e é amplamente utilizado na comunidade de engenharia, ciência de dados e estatística devido à sua integração com R, Python e Julia.

Emojis: 😎📚💻📝🚀 [https://gist.github.com/rxaviers/7360908](https://gist.github.com/rxaviers/7360908)

Para publicar direto do vscode: _quarto publish gh-pages_
