{
  "hash": "3aae2252a0736836230509cb822277db",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Vetores no Plano\"\nsubtitle: \"Capítulo 11 — Vectors and the Geometry of Space (§11.1)\"\ndescription: \"Forma de componentes, operações vetoriais, vetores unitários padrão e aplicações a força e velocidade.\"\nauthor: \"Raphael Teixeira\"\ndate: \"2026-08-10\"\ndate-modified: last-modified\ncategories: [Cálculo, Vetores, Álgebra Linear, Python]\nlivro: \"Larson & Edwards — Multivariable Calculus\"\nautor-livro: \"Ron Larson\"\ncapitulo: 11\nstatus: rascunho\nlang: pt-BR\n---\n\n## Contexto\n\nO Capítulo 11 abre a parte multivariável do livro introduzindo vetores e o sistema de\ncoordenadas tridimensional, base para o restante do texto (retas e planos no espaço,\nsuperfícies quádricas, funções de várias variáveis). Esta nota cobre apenas §11.1\n(*Vectors in the Plane*), que trata do caso bidimensional antes de estender as ideias ao\nespaço em §11.2.\n\n## Ideias centrais\n\n**Segmento de reta orientado e vetor (p. 764).** Um segmento de reta orientado\n$\\overrightarrow{PQ}$ tem ponto inicial $P$, ponto terminal $Q$ e comprimento (norma)\n$\\|\\overrightarrow{PQ}\\|$. Dois segmentos com o mesmo comprimento e direção são\n*equivalentes*; um vetor $\\mathbf{v}$ é o conjunto de todos os segmentos equivalentes a um\ndado $\\overrightarrow{PQ}$.\n\n**Forma de componentes (p. 765).** Colocando o ponto inicial na origem (posição padrão), o\nvetor fica determinado pelo ponto terminal: $\\mathbf{v} = \\langle v_1, v_2 \\rangle$. Dados\n$P(p_1, p_2)$ e $Q(q_1, q_2)$, o vetor $\\overrightarrow{PQ}$ tem componentes\n$\\langle q_1 - p_1, q_2 - p_2 \\rangle$ e comprimento\n$\\|\\mathbf{v}\\| = \\sqrt{v_1^2 + v_2^2}$. Um vetor de norma 1 é um *vetor unitário*, e\n$\\|\\mathbf{v}\\| = 0$ se e só se $\\mathbf{v}$ é o vetor zero $\\mathbf{0} = \\langle 0, 0\\rangle$.\n\n**Operações vetoriais (p. 766).** Para $\\mathbf{u} = \\langle u_1, u_2\\rangle$,\n$\\mathbf{v} = \\langle v_1, v_2\\rangle$ e escalar $c$:\n$$\n\\mathbf{u} + \\mathbf{v} = \\langle u_1 + v_1,\\, u_2 + v_2\\rangle, \\qquad\nc\\mathbf{u} = \\langle cu_1,\\, cu_2\\rangle, \\qquad\n\\mathbf{u} - \\mathbf{v} = \\mathbf{u} + (-\\mathbf{v}).\n$$\nGeometricamente, $\\mathbf{u} + \\mathbf{v}$ é a diagonal do paralelogramo com lados\n$\\mathbf{u}$ e $\\mathbf{v}$ (regra do paralelogramo), e $c\\mathbf{v}$ tem comprimento\n$|c|\\,\\|\\mathbf{v}\\|$, mesma direção de $\\mathbf{v}$ se $c>0$ e direção oposta se $c<0$.\n\n**Teorema 11.1 (propriedades de espaço vetorial).** Soma e multiplicação por escalar em\n$\\mathbb{R}^2$ satisfazem as oito propriedades de um espaço vetorial: comutatividade e\nassociatividade da soma, elemento neutro $\\mathbf{0}$, inverso aditivo $-\\mathbf{u}$,\n$c(d\\mathbf{u}) = (cd)\\mathbf{u}$, distributividade em relação a escalares e a vetores, e\n$1 \\cdot \\mathbf{u} = \\mathbf{u}$.\n\n**Teorema 11.2 (comprimento do múltiplo escalar).** $\\|c\\mathbf{v}\\| = |c|\\,\\|\\mathbf{v}\\|$.\n\n**Teorema 11.3 (vetor unitário na direção de v).** Para $\\mathbf{v} \\neq \\mathbf{0}$, o\nvetor $\\mathbf{u} = \\mathbf{v}/\\|\\mathbf{v}\\|$ tem comprimento 1 e mesma direção de\n$\\mathbf{v}$; este processo é a *normalização* de $\\mathbf{v}$.\n\n**Desigualdade triangular (p. 769).** $\\|\\mathbf{u} + \\mathbf{v}\\| \\leq \\|\\mathbf{u}\\| +\n\\|\\mathbf{v}\\|$, com igualdade apenas quando $\\mathbf{u}$ e $\\mathbf{v}$ têm a mesma\ndireção — consequência geométrica de ver $\\mathbf{u}, \\mathbf{v}$ como dois lados de um\ntriângulo.\n\n**Vetores unitários padrão (p. 769).** $\\mathbf{i} = \\langle 1, 0\\rangle$ e\n$\\mathbf{j} = \\langle 0, 1\\rangle$ permitem escrever qualquer vetor como combinação linear\n$\\mathbf{v} = v_1\\mathbf{i} + v_2\\mathbf{j}$, com $v_1, v_2$ as componentes horizontal e\nvertical. Se $\\mathbf{u}$ é unitário e $\\theta$ é o ângulo (anti-horário) a partir do eixo\n$x$ positivo, $\\mathbf{u} = \\cos\\theta\\,\\mathbf{i} + \\sin\\theta\\,\\mathbf{j}$; logo qualquer\n$\\mathbf{v}$ que faça ângulo $\\theta$ com o eixo $x$ se escreve\n$\\mathbf{v} = \\|\\mathbf{v}\\|\\cos\\theta\\,\\mathbf{i} + \\|\\mathbf{v}\\|\\sin\\theta\\,\\mathbf{j}$.\n\n**Aplicações — força e velocidade (pp. 770–771).** A força resultante sobre um objeto\nsujeito a várias forças é a soma vetorial das forças individuais (Exemplo 7: dois rebocadores\nempurrando um navio a $\\pm 20°$ da proa, cada um com 400 lb, resultam em força de\n$\\approx 752\\mathbf{i}$ lb ao longo do eixo do navio). Da mesma forma, a velocidade\nresultante de um avião sujeito a vento é a soma do vetor velocidade do avião com o vetor\nvelocidade do vento (Exemplo 8), com *bearing* (rumo) medido em graus no sentido horário a\npartir do norte.\n\n## Derivações\n\n**Prova do Teorema 11.2.** Como $c\\mathbf{v} = \\langle cv_1, cv_2\\rangle$,\n$$\n\\|c\\mathbf{v}\\| = \\sqrt{(cv_1)^2 + (cv_2)^2} = \\sqrt{c^2(v_1^2+v_2^2)} = |c|\\sqrt{v_1^2+v_2^2} = |c|\\,\\|\\mathbf{v}\\|.\n$$\n\n**Prova do Teorema 11.3.** Como $1/\\|\\mathbf{v}\\|$ é positivo, $\\mathbf{u} =\n(1/\\|\\mathbf{v}\\|)\\mathbf{v}$ tem a mesma direção de $\\mathbf{v}$. Pelo Teorema 11.2,\n$$\n\\|\\mathbf{u}\\| = \\left\\|\\frac{1}{\\|\\mathbf{v}\\|}\\mathbf{v}\\right\\| = \\left|\\frac{1}{\\|\\mathbf{v}\\|}\\right|\\|\\mathbf{v}\\| = \\frac{1}{\\|\\mathbf{v}\\|}\\|\\mathbf{v}\\| = 1.\n$$\n\n**Exemplo 7 (força resultante), refeito.** Com $\\mathbf{F}_1 = 400\\langle\\cos 20°, \\sin\n20°\\rangle$ e $\\mathbf{F}_2 = 400\\langle\\cos(-20°), \\sin(-20°)\\rangle$, a soma cancela as\ncomponentes verticais por simetria ($\\sin 20° = -\\sin(-20°)$) e dobra a componente\nhorizontal:\n$$\n\\mathbf{F} = \\mathbf{F}_1 + \\mathbf{F}_2 = 800\\cos(20°)\\,\\mathbf{i} \\approx 752\\,\\mathbf{i}.\n$$\n\n## Implementação\n\n::: {#6d3a3a92 .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\n# Exemplo 7 (p. 770): dois rebocadores, cada um exercendo 400 lb a ±20° da proa.\nF1 = 400 * np.array([np.cos(np.radians(20)), np.sin(np.radians(20))])\nF2 = 400 * np.array([np.cos(np.radians(-20)), np.sin(np.radians(-20))])\nF = F1 + F2\n\nfig, ax = plt.subplots(figsize=(6, 5))\norigin = np.zeros(2)\nfor vec, label, color in [(F1, \"F1\", \"C0\"), (F2, \"F2\", \"C1\"), (F, \"F1+F2\", \"C3\")]:\n    ax.annotate(\n        \"\", xy=vec, xytext=origin,\n        arrowprops=dict(arrowstyle=\"->\", color=color, lw=2),\n    )\n    ax.text(*(vec * 1.05), label, color=color, fontsize=11)\n\nax.set_xlim(-50, 850)\nax.set_ylim(-200, 200)\nax.set_aspect(\"equal\")\nax.axhline(0, color=\"gray\", linewidth=0.5)\nax.axvline(0, color=\"gray\", linewidth=0.5)\nax.set_title(\"Força resultante sobre o navio (Exemplo 7, §11.1)\")\nax.grid(alpha=0.3)\nplt.show()\n\nprint(f\"||F1|| = {np.linalg.norm(F1):.1f} lb, ||F2|| = {np.linalg.norm(F2):.1f} lb\")\nprint(f\"F = F1 + F2 = ({F[0]:.1f}, {F[1]:.1f}), ||F|| = {np.linalg.norm(F):.1f} lb\")\n```\n\n::: {.cell-output .cell-output-display}\n![](01-vetores-no-plano_files/figure-html/cell-2-output-1.png){width=529 height=260}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n||F1|| = 400.0 lb, ||F2|| = 400.0 lb\nF = F1 + F2 = (751.8, 0.0), ||F|| = 751.8 lb\n```\n:::\n:::\n\n\n## Conexões\n\n<!-- TODO: ainda não há outra nota deste repositório sobre vetores/álgebra linear para\nlinkar. Revisitar quando §11.2 (espaço) e §11.3–11.4 (produto escalar e vetorial) forem\nlidas. -->\n\n## Exercícios selecionados\n\n<!-- TODO: resolver e registrar aqui exercícios de §11.1 depois de trabalhados. -->\n\n## Referências\n\n[@larson2010multivariablecalculus], capítulo 11, §11.1.\n\n",
    "supporting": [
      "01-vetores-no-plano_files"
    ],
    "filters": [],
    "includes": {}
  }
}