name: Publicar Notas

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: raphateixeira/.github/.github/workflows/quarto-publish.yml@main
    with:
      needs_python: true
      needs_r: true
      r_packages: "knitr, rmarkdown"
      needs_pdf2svg: true
      needs_tinytex: true
      tinytex_packages: "pgf standalone xcolor"
